fields:
  - field: guid
    datatype: text
    source: user
    definition: global unique identifier for the observation
  - field: datasource
    datatype: keyword
    source: user
    definition: name of the datasource
  - field: verbatim_date
    datatype: text
    source: user
    definition: verbatim date
  - field: day_of_year
    datatype: integer
    source: user
    definition: day of the year. Must be between 1 and 366
  - field: year
    datatype: integer
    source: user
    definition: year of the observation
  - field: latitude
    datatype: float
    source: user
    definition: latitude with precision up to 6 decimal places
  - field: longitude
    datatype: float
    source: user
    definition: longitude with precision up to 6 decimal places
  - field: coordinate_uncertainty_meters
    datatype: integer
    source: user
    definition: coordinate uncertainty in meters
  - field: family
    datatype: keyword
    source: user
    definition: family of the organism
  - field: scientific_name
    datatype: text
    source: user
    definition: scientific name of the observed organism
  - field: taxon_rank
    datatype: text
    source: user
    definition: taxonomic rank of the scientific name
  - field: basis_of_record
    datatype: text
    source: user
    definition: basis of record of observed organism. See Darwin Core reference for values
  - field: individualID
    datatype: text
    source: user
    definition: individual ID of the observed organism
  - field: occurrenceID
    datatype: text
    source: user
    definition: occurrence ID of the observed organism
  - field: verbatim_trait
    datatype: text
    source: user
    definition: Verbatim description of the trait
  - field: trait
    datatype: text
    source: user
    definition: Trait tested. Currently "flower" or "fruit"
  - field: observed_image_guid
    datatype: text
    source: user
    definition: Globally Unique Identifier of the image
  - field: observed_image_url
    datatype: text
    source: user
    definition: URL for the image
  - field: certainty
    datatype: keyword
    source: user
    definition: Certainty of machine observation (Equivocal or Unequivocal)
  - field: model_uri
    datatype: text
    source: user
    definition: URI of the model
  - field: error_message
    datatype: text
    source: user
    definition: Error messages from processing
  - field: mapped_traits
    datatype: keyword
    source: system
    definition: Pipe delimited list of mapped traits

